const actionTypes = {
    LOGOUT: 'LOGOUT',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',

    GET_POSTS: 'GET_POSTS',
    GET_POSTS_LIMIT: 'GET_POSTS_LIMIT',
    GET_POSTS_ADMIN: 'GET_POSTS_ADMIN',
    GET_NEW_POST: 'GET_NEW_POST',
    EDIT_DATA: 'EDIT_DATA',
    RESET_DATAEDIT: 'RESET_DATAEDIT',
    GET_SAVE_POST: 'GET_SAVE_POST',
    GET_STATUS_POST: 'GET_STATUS_POST',
    GET_STATUS_ALL_POST: 'GET_STATUS_ALL_POST',

    GET_CATEGORIES: 'GET_CATEGORIES',

    GET_PRICES: 'GET_PRICES',
    GET_AREAS: 'GET_AREAS',
    GET_PROVINCES: 'GET_PROVINCES',

    //USER
    GET_CURRENT: 'GET_CURRENT',
    GET_USERS_LIMIT: 'GET_USERS_LIMIT',
    EDIT_USER_DATA: 'EDIT_USER_DATA',
    RESET_DATA_USER_EDIT: 'RESET_DATA_USER_EDIT',
}
export default actionTypes